# Generated by Django 5.1.1 on 2024-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('doctorSelect', models.CharField(max_length=100)),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('accept', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitle_Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=100)),
                ('patientID', models.BigIntegerField()),
                ('admissionDate', models.DateField()),
                ('dischargeDate', models.DateField()),
                ('serviceDescription', models.CharField(max_length=100)),
                ('totalAmount', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('netAmount', models.BigIntegerField()),
                ('paymentMethod', models.CharField(max_length=10000)),
                ('transactionID', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.BigIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('admissionDate', models.DateField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('treatmentPlan', models.CharField(max_length=100)),
                ('Medication', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('doctorNotes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
            ],
        ),
    ]
